#!/bin/bash -e

patch -Np1 -i cosmic-greeter-lto.patch
cargo fetch --locked
git lfs install --local
git remote add network-origin https://github.com/pop-os/cosmic-greeter
git lfs fetch network-origin
git lfs checkout

patch -Np1 -i cosmic-greeter-display-manager.patch
RUSTFLAGS+=" -C link-arg=-fuse-ld=mold"

just build-release --frozen
just rootdir="${1}" install
install -Dm 644 cosmic-greeter.toml -t "${1}"/etc/greetd/
install -Dm 644 debian/cosmic-greeter{.service,-daemon.service} -t "${1}"/usr/lib/systemd/system/
