#!/bin/sh -e

patch -Np1 -i cosmic-settings-daemon-lto.patch
cargo fetch --locked
sed 's/libexec/lib/g' -i Makefile src/main.rs
sed 's/sudo/wheel/g' -i data/polkit-1/rules.d/cosmic-settings-daemon.rules
export GEOCLUE_AGENT="/usr/lib/geoclue-2.0/demos/agent"
RUSTFLAGS+=" -C link-arg=-fuse-ld=lld"
make ARGS+=" --frozen --release" geoclue_agent='/usr/lib/geoclue-2.0/demos/agent'
make DESTDIR=$1 install
