#!/bin/sh -e

cargo fetch --locked
sed 's/lto = "fat"/lto = "thin"/' -i Cargo.toml
RUSTFLAGS+=" -C link-arg=-fuse-ld=lld"
make ARGS+=" --frozen --release"
make prefix='/usr' libexecdir='/usr/lib' DESTDIR=$1 install
